name: Build and Generate Domain

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List workspace contents
        run: ls -al ${{ github.workspace }}

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt update
          sudo apt install gcc libc6-dev libsodium-dev make autoconf -y

      - name: Build project
        working-directory: ${{ github.workspace }}
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Generate domain name
        working-directory: ${{ github.workspace }}
        run: |
          ./mkp224o -n ${{ secrets.GEN_NUMBER }} -d /var/lib/tor/ ${{ secrets.DOMAIN_NAME }}
